### PR TITLE
Android support and interface additions

### PR DESCRIPTION
**Pull request by dlannan**
Changes:
- Added a working build for android (GLES2 - can probably use GLES3)
- Added API methods for plot_lines, plot_histogram, text_colored and input_int4 
- Added examples for the above API changes.

### CODE REVIEW

**Comment by britzl** [comment]
The PR doesn't build and run on macOS:

```
/imgui/src/imgui/imgui_impl_metal.mm
	Line 544: cannot create __weak reference in file using manual reference counting
    __weak id weakSelf = self;
```

**Comment by dlannan-fmad** [comment]
Hi. Only Android has been tested. Mac/OSX is placeholder atm. I need to get my mac mini dev running again :)

**Comment by dlannan** [comment]
Sorry commented using my work account. I'll remove the OSX/Mac files tonight. And once I have them working, I'll submit another PR.

**Comment by britzl** [comment]
Great. Please note that the extension already works on macOS though (using the opengl implementation)! I haven't looked into what might be required for it to work on iOS as well.

**Comment by dlannan** [comment]
Oh. Im a nugget - yes, I saw you had OSX support. I was thinking of moving it to metal so that IOS could potentially be supported as well. Didnt mean to break existing functionality. Sorry. Will remove those changes.

**Comment by dlannan** [comment]
Just a question. Should there be an OSX defined check here?
https://github.com/britzl/extension-imgui/blob/97e29160b63d5a62394f44ffa25ce4d0d77625c2/imgui/src/imgui/imconfig.h#L1-L10

**Comment by britzl** [comment]
> Should there be an OSX defined check here?

It is my understanding that there is no need to specify a GL loader on OSX (at least not when using Dear ImGUI from Defold). So for OSX we fallback to the empty dummy loader.

**Comment by dlannan** [comment]
Ok. Probably has the binding in the staticlibs that are compiled with the build. Thats good to know. Thanks.

**Review by britzl — APPROVED** [review]
Thank you!

**Pull request merged**
